src/MyFLsite/MyFLsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView
from django.conf.urls.static import static #DEBUG# Comment out on production server
from django.conf import settings #DEBUG# Currently only used for above debug line

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'MyFLsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    #General
                       url(r'^$', TemplateView.as_view(template_name='main/home.html'),
                           kwargs={'widgets':[
                               {'img':'images/LabFBTUGentlogo.png'},
                               {'img':'images/basespace-brand.png'},
                               {'img':'images/n2nLogo.png'},
                               #{'img':'images/ugentLogo.png'},
                               {'img':'images/MyFLqLogo.png'}]}),
    url(r'^source-files/$', TemplateView.as_view(template_name='main/sourcefiles.html')),
    url(r'^contact/$','main.views.contact'),
    url(r'^contact/thanks/$',TemplateView.as_view(template_name='main/thanks.html')),
                       url(r'^about/$', TemplateView.as_view(template_name='main/about.html'),
                           kwargs={'widgets':[
                               {'img':'images/group.png', 'caption':
'''MyFLq was developed by researchers at Ghent University's
Laboratory of Pharmaceutical Biotechnology and led by Professor
and Laboratory Director Dieter Deforce, Ph.D (middle), postdoctoral
researcher, Filip Van Nieuwerburgh, Ph.D. (right), and Ph.D. student
Christophe Van Neste (left).''','style':'border-radius:20px;'}
                           ]}),
    
    #Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),
    url(r'^register/$','main.views.register'),
    
    #MyFLq (only after login)
    url(r'^myflq/', include('myflq.urls')),
    url(r'^(?P<flad>flad|FLAD|flax|FLAX)/', include('flad.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #DEBUG# Comment last line out on production server

src/MyFLsite/flad/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required#, permission_required
from django.views.generic import TemplateView

urlpatterns = patterns('',
    #All keys in kwargs need to be strings, with TemplateView they are passed to the context
    url(r'^$', TemplateView.as_view(template_name='flad/home.html'),kwargs={'flad':True}),
    url(r'^query/$', TemplateView.as_view(template_name='flad/base.html'),kwargs={'flad':True}),
    url(r'^testing/$', TemplateView.as_view(template_name='flad/testing.html'),kwargs={'flad':True}),
    url(r'^help/$', TemplateView.as_view(template_name='flad/help.html'),kwargs={'flad':True}),
    url(r'^registration/$','flad.views.registration'),
    url(r'^getseq/(?P<mode>xml/|plain/|)(?P<fladid>[FLT](L\d+)?[AX][\dA-F]{2,})'+
        r'(?P<transform>t[oc]((\d+)(((\.\d+)?[ACTGNd])+)(i?))*)?/$',
        'flad.views.getsequence'),
    url(r'^getid/(?P<mode>xml/|plain/|)(?P<validate>validate/|)((?P<locus>[a-zA-Z][-\w]+)/)?(?P<seq>[ACTGN]*)$','flad.views.getid'),
                       #for locus regex: first letter should be a letter, following symbols alphanumeric or '-'
    url(r'^(?P<message>.*)/$','flad.views.error'),
)

src/MyFLsite/myflq/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required#, permission_required
from django.views.generic import TemplateView

urlpatterns = patterns('',
    #All keys in kwargs need to be strings, with TemplateView they are passed to the context
    url(r'^$', login_required(TemplateView.as_view(template_name='myflq/home.html')),kwargs={'myflq':True}), 
    url(r'^setup/$','myflq.views.setup'),
    url(r'^paf/(?P<configuration>\d+)/$','myflq.views.paf'),
    url(r'^analysis/$','myflq.views.analysis'),
    url(r'^results/$','myflq.views.results'),
    url(r'^results/view/((?P<analysis>\d+)/)?$','myflq.views.result'),
    url(r'^profile/((?P<analysis>\d+)/)?$','myflq.views.profile'),
    url(r'^help/$', login_required(TemplateView.as_view(template_name='myflq/help.html')),kwargs={'myflq':True}), 
)

src/MyFLsite/myflq/models.py
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.

#Setup
##some symbols allowed in django username that are not allowed in MySQL name
noSQLname = {'@','+','-','.'}

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
#Previous lambda functions that needed to be named for migrations to work
def lociUpload(instance,filename): return 'locifiles/'+instance.fulldbname()+'.csv'
def alleleUpload(instance,filename): return 'allelefiles/'+instance.fulldbname()+'.csv'
class UserResources(models.Model):
    """
    This model indicates which databases the user has at their disposal.
    """
    user = models.ForeignKey(User)
    dbname = models.CharField(max_length=200,verbose_name="configuration name",
                              help_text='Choose a sensible name for your configuration',
         validators=[RegexValidator(regex=r'^\w*$', message='Should ony contain alphanumericals.')])
    description = models.TextField(verbose_name="configuration description",null=True,blank=True)
    populationdb = models.BooleanField(default=False,verbose_name='population database',help_text=
        '''Check this box if this configuration will be used to build up
        a population allele frequency table.'''
    )
    lociFile = models.FileField(verbose_name='loci configuration file',
                                upload_to=lociUpload,
                                help_text="The loci file should contain one line for every locus with the following structure:<br />\
                                LocusName,LocusType(a number for STR indicating repeat length or 'SNP' for other \
                                loci),forward primer, reverse primer")
    alleleFile = models.FileField(verbose_name='allele database file',
                                  null=True,blank=True,#With new config format all necessary info can be in lociFile for first analyses
                                  upload_to=alleleUpload,
                                  help_text="This file should contain all known alleles within the population. Each line should have\
                                  the following structure:<br />Locus name, STR number for STR loci/Allele name for SNP loci, Sequence")
    creationDate = models.DateField(auto_now_add=True)
    lastUpDate = models.DateTimeField(null=True,blank=True) #creationTime from last Allele added, to check if config needs updating

    def __str__(self):
        return self.dbname
        
    def dbusername(self):
        """
        This is the username for the database, linked to the MyFLsite current user 
        """
        if (not set(self.user.username) & noSQLname) and len(self.user.username) <= 10:
            return 'myfls_'+self.user.username
        else:
            return 'myflsid_'+str(self.user.id)
    
    def fulldbname(self):
        """
        This is the name how it will be used in the database system.
        It includes a general MyFLsite prefix, and the username so that
        different users can use the same short dbname
        """
        return self.dbusername()+'_'+self.dbname

    def countNonValidatedAlleles(self):
        """
        This counts the number of NA or non validated alleles.
        It is not good practice to have too many such alleles linked to a configuration.
        Profiles that report such NA alleles should be tracked, and the NA allele
        should either be validated and get a FLADid or be removed from the profile.
        """
        return NotImplemented
    
class Locus(models.Model):
    """
    This model lists all loci analyzed per configuration
    """
    configuration = models.ForeignKey(UserResources)
    name = models.CharField(max_length=200)
    locusType = models.IntegerField(null=True,blank=True,verbose_name='type')
    forwardPrimer = models.CharField(max_length=200)
    reversePrimer = models.CharField(max_length=200)
    #For backwards compatibility following fields are all null=True,blank=True as they were not in previous versions
    refnumber = models.FloatField(null=True,blank=True,verbose_name='reference repeat number') #For STR loci alleles #TODO add validator
    refsequence = models.CharField(null=True,blank=True,max_length=1000) 
    refmask = models.CharField(null=True,blank=True,max_length=1000) #TODO add validator same length as refsequence
    
    class Meta:
        unique_together = ("configuration", "name")
        ordering = ('name',)
    
    def __str__(self):
        return self.name
        
#Analysis
from django.core.exceptions import ValidationError
def validate_percentage(value):
    if value and not (0 < value <= 1):
        raise ValidationError('{} is not within [0-1]'.format(value))

import re, uuid
goodSeqFileRegex = re.compile(r'.*(\.fasta|\.fasta\.gz|\.fastq|\.fastq\.gz)$')
def generateFileName(instance,filename):
    instance.originalFilename = filename
    return 'fastqfiles/'+str(uuid.uuid4())+goodSeqFileRegex.match(filename).groups()[0]

class Analysis(models.Model):
    """
    Gathers all information for starting an analysis.
    """
    name = models.TextField(verbose_name="analysis name",null=True,blank=True)
    configuration = models.ForeignKey(UserResources)
    fastq = models.FileField(verbose_name="fast[a|q][.gz]",upload_to=generateFileName,blank=True,
                             validators=[RegexValidator(regex=goodSeqFileRegex, message='Only fast[a|q][gz] files.')],
                             help_text='''Provide the file either by uploading or by choosing a previously uploaded one.
                             A filename should end with either: .fasta, .fasta.gz, .fastq, or, .fastq.gz'''
    )
        #blank=True=>Form processing needs to make fastq required
    originalFilename = models.CharField(max_length=128,null=True)
    negativeReadsFilter = models.BooleanField(default=True,help_text=
        '''Long flanks could overlap within small unknown alleles, or their
        stutters. This option filters them, but reports on their abundance.'''
    )
    kMerAssign = models.IntegerField(default=0,help_text=
                '''Reads can be assigned to loci by looking up the presence
                of primer kmers in the read. This allows for processing of
                reads with errors in the primers. Default value: 0 == not using it.
                When using, recommended values are 5,6,...''')
    primerBuffer = models.IntegerField(default=0,help_text=
                '''The ends of the primers are not used for assigning the reads
                to loci. Choosing a higher primerBuffer therefore means the
                locus assignment will be less specific, but more reads will be
                asigned.'''
    )
    flankOut = models.BooleanField(default=False,help_text=mark_safe(
                '''Options:<br />
                Flankout analysis. This analysis will only consider the region of interest
                of the different population alleles, based on the selected configuration
                allele database.<br /><br />
                Variant discovery. For population studies, where the scope is to find new
                variants, this option should be selected. It will report on all new variants
                discovered between the primers for the loci considered in the configuration.
                This option should also be chosen if you see a large amount of negative reads
                in a flankout analyis, or a high abundant unique read with very poor flanks.''')
    )
    stutterBuffer = models.IntegerField(default=1,help_text=
                '''The stutters of the smallest allele for a locus are normally not in
                the database. Default value of stutterBuffer is 1, which allows them to
                be seen in the analysis as flanking out is performed with a flank 1 repeat
                unit smaller.'''
    )
    useCompress = models.BooleanField(default=True,help_text=
                '''Homopolymers are a common problem for sequencing. With useCompress
                activated, flanks are removed taking account for possible homopolymer 
                issues.'''
    )
    withAlignment = models.BooleanField(default=False,help_text=
                '''If this option is activated, flanks are removed with our alignment
                algorithm, instead of the k-mer based flexible flanking.'''
    )
    threshold = models.FloatField(default=0.005,help_text=
                '''Unique reads with an abundance lower than this value, are discarded.
                It is reported how many reads were discarded in this way.'''
    )
    clusterInfo = models.BooleanField(default=True,help_text=
                '''With this option activated, unique reads within a loci are compared
                to each other. Reads that differ little are annotated as such.
                Does require more processing time.'''
    )
    randomSubset = models.FloatField(blank=True,null=True,validators=[validate_percentage], 
                help_text= '''Should be between 0 and 1, or blank.
                Indicates the percentage of the file that will be used for processing.
                This allows to get an initial quick analysis for low values.'''
    )
    progress = models.CharField(max_length=2,default='Q',choices=[('Q','Queued'),('P','Processing'),('F','Finished'),('FA','Failed')])
    creationTime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-creationTime']

    def __str__(self):
        return 'Analysis: config = '+str(self.configuration)+', file = '+self.originalFilename+' [settings => '+ \
            'negativeReadsFilter = '+str(self.negativeReadsFilter)+', '+ \
            'primerBuffer = '+str(self.primerBuffer)+', '+ \
            'flankOut = '+str(self.flankOut)+' ,'+ \
            'stutterBuffer = '+str(self.stutterBuffer)+', '+ \
            'useCompress = '+str(self.useCompress)+', '+ \

src/MyFLsite/myflq/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import modelformset_factory

from myflq.models import UserResources,Analysis,Allele,FLADconfig

#Setup
from django.core.validators import RegexValidator
class ConfigurationForm(ModelForm):
    class Meta:
        model = UserResources
        exclude = ['user','creationDate','lastUpDate']
        widgets = {
            'description': forms.Textarea(attrs={'rows':2, 'cols':50}),
        }
        
    def clean_lociFile(self):
        locifile = self.cleaned_data.get('lociFile',False)
        if locifile:
            if locifile.size > 5*1024*1024:
                raise forms.ValidationError("Loci file too large ( > 5 MB )")
            return locifile
        else:
            raise forms.ValidationError("Couldn't read uploaded file")

    def clean_alleleFile(self):
        afile = self.cleaned_data.get('alleleFile',False)
        if afile:
            if afile.size > 5*1024*1024:
                raise forms.ValidationError("Allele file too large ( > 5 MB )")
            return afile
        else:
            pass
            #raise forms.ValidationError("Couldn't read uploaded file")
            #TODO extended validation of file format
    #Webserver configuration:  !!!
    #    Configure the Web server to limit the allowed upload body size. 
    #    e.g. if using Apache, set the LimitRequestBody setting. 
    #    This will mean if a user tries to upload too much, they'll get an error page configurable in Apache
        

#Analysis
class FastqChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.originalFilename

def analysisform_factory(db_queryset,upfiles_queryset):
    uniqueUpFiles = {up['originalFilename']:up['id'] for up in upfiles_queryset.values('id','originalFilename')}.values()
    class AnalysisForm(ModelForm):
        configuration = forms.ModelChoiceField(db_queryset)
        prevUploadedFiles = FastqChoiceField(upfiles_queryset.filter(id__in=uniqueUpFiles),required=False,empty_label="(Upload file instead)")
        
        class Meta:
            model = Analysis
            exclude = ['originalFilename','progress','creationTime']
            widgets = {
                'name': forms.Textarea(attrs={'rows':1, 'cols':30}),
            }
        
        #def clean_fastq(self): #when cleaning needs to combine different form fields
        # do that from general 'clean' method
        def clean(self):
            fastq = self.cleaned_data.get('fastq',False)
            if not fastq:
                prevUploadedFile = self.cleaned_data.get('prevUploadedFiles',False)
                if prevUploadedFile:
                    self.cleaned_data['fastq'] = prevUploadedFile.fastq
                    self.cleaned_data['originalFilename'] = prevUploadedFile.originalFilename
                else: raise forms.ValidationError('No FASTQ provided.')
            #return fastq
            return self.cleaned_data
        
    return AnalysisForm

#Allele
class NewAlleleForm(ModelForm):
    class Meta:
        model = Allele
        fields = ('sequence',)
NewAlleleFactory = modelformset_factory(Allele,NewAlleleForm)

#FLAD configuration
class FLADconfigForm(ModelForm):
    class Meta:
        model = FLADconfig
        exclude = ['user']

src/MyFLsite/myflq/templates/myflq/analysis.html
{% extends "base_ajax.html" %}

{% block extrahead %}
{{  block.super }} {# block.super loads jquery #}
<script>
function refreshProgress(){
    $.getJSON('.',function(data) {
        var pks_present = [];
        $.each(data, function(entryIndex,entry) {
            //console.log(entry.pk+' '+entry.fields.progress);
            pks_present.push(entry.pk)
            if ($('td.progress#'+entry.pk).html() != entry.fields.progress)
                $('td.progress#'+entry.pk).html(entry.fields.progress)
        });
        //console.log(pks_present)
        $('td.progress').filter(function() {return (pks_present.indexOf(Number(this.id)) == -1)}).parent().hide()
    })
}
$(document).ready(function() {setInterval("refreshProgress();", 30000)}) //checks every half minute

function changeAim() {
  $("#analysisAim").html(($("#analysisAim").html() == "Variant discovery") ? "Flankout analysis":"Variant discovery");
  $(".flankOut").toggle();
  $("#id_flankOut").prop("checked",$("#id_flankOut").prop("checked")?false:true)
}
</script>
{% endblock %}

{% block content %}
<h1> Analysis </h1>

<h2> Submit analysis request </h2>
    <form action='.' enctype="multipart/form-data" method='post'>
        {% csrf_token %}
        {{ analysisform.management_form }}
        {{ analysisform.errors }}
        {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}        
        
        <table>
        <tr><td><label for="{{ analysisform.name.id_for_label }}">{{ analysisform.name.label }}</label></td>
        <td>{{ analysisform.name }}</td></tr>

        <tr><td><label for="{{ analysisform.configuration.id_for_label }}">{{ analysisform.configuration.label }}</label></td>
        <td>{{ analysisform.configuration }}</td></tr>

	<tr><td><label class="helponhover" for="analysisAim">Analysis scope</label><span class="helptext">{{ analysisform.flankOut.help_text }}</span></td></td>
	<td><button id="analysisAim" type="button" onClick="changeAim();">{% if analysisform.flankOut.value %}Flankout analysis{% else %}Variant discovery{% endif %}</button></td></tr>

	<tr height="10px"></tr>
        
        <tr><td><label class="helponhover" for="{{ analysisform.fastq.id_for_label }}">{{ analysisform.fastq.label }}</label>
	    <span class="helptext">{{ analysisform.fastq.help_text }}</span>
	  </td>
        <td>{{ analysisform.fastq }}</td></tr>
        <tr><td>Or previously uploaded file: </td>	
<td>{{ analysisform.prevUploadedFiles }}</td></tr>
        </table>

        <p style="display:none;">
	  {{ analysisform.flankOut }}
	  {{ analysisform.negativeReadsFilter }}
	</p>

        <div style="float:left;">
            <h3>General</h3>
            <table>
            <tr><td><label class="helponhover" for="{{ analysisform.primerBuffer.id_for_label }}">{{ analysisform.primerBuffer.label }}</label>
 <span class="helptext">{{ analysisform.primerBuffer.help_text }}</span></td>
              <td>{{ analysisform.primerBuffer }}</td></tr>
	    <tr><td><label class="helponhover" for="{{ analysisform.kMerAssign.id_for_label }}">{{ analysisform.kMerAssign.label }}</label>
 <span class="helptext">{{ analysisform.kMerAssign.help_text }}</span></td>
            <td>{{ analysisform.kMerAssign }}</td></tr>
            <tr><td><label class="helponhover" for="{{ analysisform.threshold.id_for_label }}">{{ analysisform.threshold.label }}</label>
 <span class="helptext">{{ analysisform.threshold.help_text }}</span></td>
            <td>{{ analysisform.threshold }}</td></tr>
            <tr><td><label class="helponhover" for="{{ analysisform.randomSubset.id_for_label }}">{{ analysisform.randomSubset.label }}</label>
 <span class="helptext">{{ analysisform.randomSubset.help_text }}</span></td>
            <td>{{ analysisform.randomSubset }}</td></tr>            
            <tr><td><label class="helponhover" for="{{ analysisform.clusterInfo.id_for_label }}">{{ analysisform.clusterInfo.label }}</label>
 <span class="helptext">{{ analysisform.clusterInfo.help_text }}</span></td>
            <td>{{ analysisform.randomSubset }}</td></tr>
            </table>
        </div>
        
        <div style="float:left;margin-left:20px;">
            <h3 class="flankOut" {% if not analysisform.flankOut.value %}style="display:none;"{% endif %}>Flankout options</h3>
            <table class="flankOut" {% if not analysisform.flankOut.value %}style="display:none;"{% endif %}>
            <tr><td><label class="helponhover" for="{{ analysisform.stutterBuffer.id_for_label }}">{{ analysisform.stutterBuffer.label }}</label>
 <span class="helptext">{{ analysisform.stutterBuffer.help_text }}</span></td>
            <td>{{ analysisform.stutterBuffer }}</td></tr>

            <tr><td><label class="helponhover" for="{{ analysisform.useCompress.id_for_label }}">{{ analysisform.useCompress.label }}</label>
 <span class="helptext">{{ analysisform.useCompress.help_text }}</span></td>
            <td>{{ analysisform.useCompress }}</td></tr>            
            <tr><td><label class="helponhover" for="{{ analysisform.withAlignment.id_for_label }}">{{ analysisform.withAlignment.label }}</label>
 <span class="helptext">{{ analysisform.withAlignment.help_text }}</span></td>
            <td>{{ analysisform.withAlignment }}</td></tr> 
            </table>
        </div>
        
        <div style="clear:both;">
            <input type="hidden" name="submitaction" value="analysisform" />
            <input type="submit" value="Submit" />
        </div>
    </form>

<hr />

<h2>Progress</h2>

{% if processes %}
<table border="1">
<tr><td></td><td>Configuration</td><td>Filename</td><td>Status</td></tr>
{% for process in processes %}
<tr><td>{{ forloop.counter }}</td><td>{{ process.configuration }}</td><td>{{ process.originalFilename }}</td><td class='progress' id='{{  process.pk }}'>{{ process.get_progress_display }}</td></tr>
{% endfor %}
</table>

{% else %}
<p>Currently, no analysis running.
{% endif %}

{% endblock %}

src/MyFLsite/myflq/templates/myflq/help.html
{% extends "base.html" %}

{% block title %}MyFLq app{% endblock %}

{% block content %}
<h1> MyFLq help </h1>

The help page will be a step-by-step tutorial, with an index to find relevant information.<br /> <br />
Under construction
{% endblock %}

src/MyFLsite/myflq/templates/myflq/home.html
{% extends "base.html" %}

{% block title %}MyFLq app{% endblock %}

{% block content %}
<h1> MyFLq </h1>
<h2>Workflow</h2>
<ol>
  <li>
    Configure general (loci/alleles) specifications in <a href="/myflq/setup">Setup</a>
    <ul>
      <li>Make a different configuration if the analysis needs different loci/alleles from previous analyses</li>
      <li>Upload a file in the correct format for the loci configuration</li>
      <li>Add the allele databank for the analysis by uploading a file in the correct format</li>
      <li>submit the settings</li>
    </ul>
  </li>
  <li>
    Choose a file to analyze and appropriate parameters in <a href="/myflq/analysis">Analysis</a>
    <ul>
      <li>After submitting the analysis request, it will show its progress state</li>
    </ul>
  </li>
  <li>
    Retrieve the outcome in  <a href="/myflq/results">Results</a>
    <ul>
      <li>Select the analysis for which you want to visualize results</li>
    </ul>
  </li>
</ol>

<h2>BaseSpace</h2>
BaseSpace users that want to use forensic.UGent.be for custom loci and alleles csv file, need to make a configuration in  <a href="/myflq/setup">Setup</a> as outlined above. 
<br />
When the configuration is uploaded, you can right-click and copy the url-address respectively for the loci file and the allele file, and paste it in the appropriate textbox on the BaseSpace MyFLq analysis launch page.

<h2>Help</h2>
For extensive help and a step-by-step tutorial, follow the link <a href="https://github.com/beukueb/myflq#workflow-for-forensicugent-or-a-local-myflq-installation">here</a>.<br />
The menu bar help, will pop up a new window.<br />
Use it during your workflow to not interrupt it.
{% endblock %}

src/MyFLsite/myflq/templates/myflq/paf.html
{% extends "base_ajax.html" %}
{% load staticfiles %}

{% block content %}
<h1> Population allele frequencies </h1>
<h2>Configuration {{ configuration }}</h2>


<table>
  <tr>
    <td></td>
    <td style="color:#50ade5;">
      Locus
    </td>
    <td style="color:#50ade5;">
      Original name
    </td>
    <td style="color:#50ade5;">
      FLADid
    </td>
    <td style="color:#50ade5;">
      {% if configuration.populationdb %}
       Population count
      {% else %}
       Population frequency
      {% endif %}
    </td>
  </tr>
{% for allele in configuration.allele_set.all %}
<tr>
  <td style="color:#50ade5;">
    {{ forloop.counter }}
  </td>
  <td>
    {{ allele.locus }}
  </td>
  <td>
    {{ allele.name }}
  </td>
  <td>
    {{ allele.FLADid }}
  </td>
  <td style="text-align:right;">
    {% if configuration.populationdb %}
     {{ allele.reports.count }}
    {% else %}
     {{ allele.initialPopstat }}
    {% endif %}
  </td>
</tr>
{% endfor %}
</table>


{% endblock %}

src/MyFLsite/myflq/templates/myflq/profile.html
{% extends "base_ajax.html" %}
{% load staticfiles %}

{% block content %}
<h2>
  Profile for
  <a style="text-decoration:none;" href="/myflq/results/view/{{ profile.analysis_id }}/">{{ profile.analysis.originalFilename }}</a>
</h2>

<p>
  Profile thresholds<br />
  => minimal abundance: {{ profile.threshold }}% <br />
  => minimal read count: {{ profile.minimalReads }}
</p>

{% if profileError %}
<p>
  {{ profileError }}
</p>
{% endif %}

<table>
{% for locus in profile.as_table %}
<tr>
  {% for allele in locus  %}
    {% if forloop.first %}
    <td style="color:#50ade5;">
    {% else %}
    <td> 
    {% endif %}
    {{ allele }}
  </td>
  {% endfor %}
</tr>
{% endfor %}
</table>

<hr />
{% if profile.isValid %}
 {% if profile.analysis.configuration.populationdb and not profile.analysis.flankOut %}
<script>
  var inProcess = false;
  function toggleDatabase() {
    if (inProcess != true) {
      inProcess = true;
      $.getJSON('.',function(data) {
        $('#toggleDB').text(($('#toggleDB').text()=='Add to population database')?'Remove from population database':'Add to population database');
        inProcess = false;
      });
    }
  }
</script>
 {% if profile.inAlleleDatabase %}
   <button id="toggleDB" onclick="toggleDatabase();">Remove from population database</button>
 {% else %}
   <button id="toggleDB" onclick="toggleDatabase();">Add to population database</button>
 {% endif %}
 {% endif %}
<script>
  function calcRMNE() {
   alert('RMNE functionality not yet active. Let us know if you require this functionality urgently.');
  }
</script>     
<button onclick="calcRMNE();">Calculate RMNE</button>
{% if profile.analysis.configuration.populationdb %}
<p>
  As the configuration with which this profile was obtained, is meant to build up a population database, it is advised to use the RMNE values only for testing, and not for reporting externally.
</p>
{% endif %}
{% else %}
<p>
  This profile contains non validated alleles.<br />
  It cannot be added to a population database. RMNE values cannot be calculated.
</p>
{% endif %}

{% endblock %}

src/MyFLsite/myflq/templates/myflq/results.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<h1> Results </h1>

<h2>All results</h2>

{% if processes %}
<form action='view/' method='post'>
    {% csrf_token %}
    <table border="1">
    <tr><td></td><td>Configuration</td><td>Date</td><td>Filename</td><td>Status</td></tr>
    {% for process in processes %}
        <tr>
	  <td>{{ forloop.counter }}</td>
	  <td>{{ process.configuration }}</td>
	  <td>{{ process.creationTime|date:"D d M Y" }}</td>
	  <td>{{ process.originalFilename }}</td>
	  <td>{{ process.get_progress_display }}</td>
        <td><input type="radio" name="viewResult" value="{{ process.id }}" {% if forloop.first %} checked {% endif %}></td></tr>
    {% endfor %}
    </table>
    <br />
    <input type="submit" value="View result" />
</form>

{% else %}
<p>Currently, no analyses available.
{% endif %}

{% endblock %}